name = "fhir_client_httpc"
version = "0.8.0"

description = "r4 httpc client layer - see https://hexdocs.pm/fhir/ "
licences = ["MIT"]
repository = { type = "github", user = "PotatoEMR", repo = "fhir_client_httpc" }

links = [
  { title = "Documentation", href = "https://hexdocs.pm/fhir/" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
fhir = "0.8.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_time = ">= 1.7.0 and < 2.0.0"
